name: FoodTech_Build
 
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
  

env:
  ECR_REPOSITORY: foodtech
  EKS_CLUSTER_NAME: foodtech-eks-cluster
  AWS_REGION: us-east-1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set short git commit SHA
        id: commit
        uses: prompt/actions-commit-hash@v3

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Package
          path: build/libs
          
      - name: Cache SonarCloud dependencies
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-${{ hashFiles('**/*.java') }}
       
      - name: Build and analyze with SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Token armazenado como segredo no GitHub
        run: |
            chmod +x ./gradlew # Adiciona permissão de execução
            ./gradlew clean build sonar \
            -Dsonar.projectKey=grupo27-6soat-fiap_produto-fase04 \
            -Dsonar.organization=grupo27-6soat-fiap \
            -Dsonar.host.url=https://sonarcloud.io
          
# sed -i.bak "s|jdbc:postgresql://postgres-svc:5432/postgres|jdbc:postgresql://$RDS_HOSTNAME:5432/postgres|g" k8s/deployment-app.yml && \
